name: 機能リクエスト
description: 新機能の提案をする
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: "## 機能リクエストフォーム"
  - type: textarea
    id: use-case
    attributes:
      label: この機能リクエストはいつ役に立ちますか
      description: 役に立つシチュエーションを記載してください。取り組む優先度の参考にさせていただきます。
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: 機能リクエストの内容
      description: 実現してほしい内容を説明してください。
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 他に検討した代替案
      description: 検討した他の機能があれば説明してください。
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: その他
      description: 役立つリンクやスクリーンショット、デザイン案などあれば追加してください。
    validations:
      required: false
